spring:
  application:
    name: user-center

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://124.221.33.157:3306/yupao?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/yupao?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
#    password: yyy2331989
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
  #session失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #redis 配置
  redis:
    port: 6379
#    host: 124.221.33.157
    host: localhost
    database: 1
#    password: yyy2331989
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
#        domain: 124.221.33.157
        domain: localhost
        max-age: 2592000
  address: 0.0.0.0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
